# -*- coding: utf-8 -*-
"""ex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eBq1GGq-KrpVqenJTfG34P0nEIeQstnf
"""

import twstock
import pandas as pd
# reference https://github.com/mlouielu/twstock

stock_ids = ['1102','1103','2330']
start_year = 2025
start_month = 1

for sid in stock_ids:
  stock = twstock.Stock(sid)
  target_price = stock.fetch_from(start_year, start_month)  #取用yyyy/mm至今每天的交易資料
  #title
  name_attribute = [
      'Date', 'Capacity', 'Turnover', 'Open', 'High', 'Low', 'Close', 'Change',
      'Transaction'
  ]
  ma_p = stock.moving_average(stock.price, 5)     # 五日均價
  ma_c = stock.moving_average(stock.capacity, 5)    # 五日均量
  ma_br = stock.ma_bias_ratio(5, 10)          # 五日、十日乖離值

  #transform list to data sheet
  df = pd.DataFrame(columns=name_attribute, data=target_price)
  df['MA_P'] = [0,0,0,0]+ma_p
  df['MA_C'] = [0,0,0,0]+ma_c
  df['MA_BR'] = [0,0,0,0,0,0,0,0,0]+ma_br
  df.to_csv(f"{sid}.csv", index=False)